# Generated by Django 4.1.7 on 2023-03-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdata",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(upload_to="media/uploads/"),
        ),
    ]
